"""remove flight number column

Revision ID: 484b554d6e26
Revises: 03ae95d10dcb
Create Date: 2026-03-04 15:52:19.194736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484b554d6e26'
down_revision: Union[str, Sequence[str], None] = '03ae95d10dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('flight_number')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_number', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
